"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

from django.utils.safestring import mark_safe
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-h-=de*p=7cbxeqhjac-kp*)7qj&ld&!aof@1xp2sr)-wf92+ij'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

load_dotenv()
# Application definition

AUTH_USER_MODEL='core.User'

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'oauth2_provider',
    'rest_framework',
    'core',
    'corsheaders',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'oauth2_provider.contrib.rest_framework.OAuth2Authentication',
    )
}

CORS_ALLOW_ALL_ORIGINS=True

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'restaurantdb',
        'USER': 'root',
        'PASSWORD': 'root',
        'HOST': '',
        'PORT': '',
    }
}

import cloudinary
cloudinary.config(
    cloud_name="dcvwzsnhj",
    api_key="883475597356838",
    api_secret="CDmA4lX1Id5lpVLp9-yRictKOFc",
)
# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

CLIENT_ID='76dV7XP4v9t9IbMP3y6SDf6JQbrafKJ15ImAjUaR'
CLIENT_SECRET='9FyzyEwTwIPGxRdvBqAshkLRiUculQfhmq71EPzlxKChyRGs14lnWIbt5rvR9MwJJs0k7hteXPzYCkB8uYFRV1B9Mu1yAeUKphzPeastWiBA73blFsxEFtMRIV9l54aM'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

JAZZMIN_SETTINGS = {
    "site_title": "Nhà Hàng Admin",
    "site_header": "Quản Lý Nhà Hàng",
    "site_brand": "Restaurant System",
    "welcome_sign": "Chào mừng quay trở lại trang quản trị!",
    "search_model": ["core.Order", "core.Bill"],

    "topmenu_links": [
        {"name": "Trang chủ", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": mark_safe('<i class="fas fa-chart-pie mr-1"></i> Xem Thống Kê'), "url": "admin:restaurant_stats","icon": "fas fa-chart-pie"},
    ],

    "icons": {
        "auth": "fas fa-users-cog",
        "core.User": "fas fa-users",
        "core.Category": "fas fa-list",
        "core.Food": "fas fa-utensils",
        "core.FoodIngredient": "fas fa-cubes",
        "core.FoodReview": "fas fa-star",
        "core.Ingredient": "fas fa-carrot",
        "core.Supplier": "fas fa-truck",
        "core.ImportReceipt": "fas fa-file-import",
        "core.Order": "fas fa-shopping-cart",
        "core.Bill": "fas fa-file-invoice-dollar",
        "core.Payment": "fas fa-credit-card",
        "core.RestaurantTable": "fas fa-chair",
        "core.Reservation": "fas fa-calendar-alt",
        "core.Voucher": "fas fa-ticket-alt",
    },
}
