# Generated by Django 5.2.15 on 2026-07-22 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category_image_alter_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='guest_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='reservation',
            name='guest_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
