# Generated by Django 5.2.15 on 2026-08-02 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_reservation_guest_name_reservation_guest_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterUniqueTogether(
            name='payment',
            unique_together={('bill', 'payment_method')},
        ),
    ]
