# Generated by Django 5.2.15 on 2026-08-07 08:03

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_phone_alter_payment_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='voucher',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
